os: osx
language: dart
dart:
  - stable
before_install:
  - brew update
  - brew tap dart-lang/dart
  - brew install dartium
#  - brew install lcov
script:
   - pub run test -p dartium
#  - pub get --packages-dir
#  - pub run dart_dev coverage
#  - bash <(curl -s https://codecov.io/bash)
