os: osx
language: dart
dart:
  - stable
before_install:
  - brew update
  - brew install lcov
script:
  - pub get --packages-dir
  - pub run dart_dev coverage
  - bash <(curl -s https://codecov.io/bash)